# Generated by Django 4.0.4 on 2022-07-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpeg', upload_to='profile_images'),
        ),
    ]
