# Generated by Django 4.0.4 on 2022-07-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_posteo_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='autor',
            field=models.CharField(max_length=250),
        ),
    ]
