# Generated by Django 4.0.4 on 2022-07-04 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_posteo_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
